#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx prettier --write common/* && npx eslint --fix common/* && npx prettier --write test/* && npx eslint --fix test/* && npx prettier --write core/* && npx eslint --fix core/* && yarn run version
